create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

alter table public.messages enable row level security;

drop policy if exists "Allow anonymous read access to messages" on public.messages;
create policy "Allow anonymous read access to messages"
  on public.messages
  for select
  to anon
  using (true);

drop policy if exists "Allow anonymous insert access to messages" on public.messages;
create policy "Allow anonymous insert access to messages"
  on public.messages
  for insert
  to anon
  with check (char_length(trim(content)) > 0);
